name = "baba300/amvote"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v2"
license = "Apache-2.0"
description = "Aiken contracts for project 'baba300/amvote'"

[repository]
user = "baba300"
project = "amvote"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.1.0"
source = "github"

[config]
